#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "10.132.141.50";
$SERVER_PORT = 15442;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
